image: fedora
testStage : 
  stage: test
  before_script:
    - dnf -y install dnf-plugins-core
    - dnf -y config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
    - dnf config-manager --set-enabled docker-ce-test
    - dnf makecache
    - dnf -y install docker-ce
    - /etc/init.d/docker start 
    - docker run hello-world
    - echo "docker installed"
  script:
    - docker build -t amarnaththillai/docker-react -f Dockerfile.dev .
    - docker run amarnaththillai/docker-react npm run test -- --coverage

production: 
  stage: deploy
  script:
  - dnf update -y
  - dnf install -y ruby-devel
  - gem install dpl
  - dpl --provider="elasticbeanstalk" --access-key-id="$AWS_DOCKER_REACT_ACCESS_KEY" --secret-access-key="$AWS_DOCKER_REACT_SECRECT_KEY" --app="docker-react" --env="DockerReact-env" --region="eu-central-1"  --bucket_name="elasticbeanstalk-eu-central-1-852664985265" --bucket_path="docker-react"
  only: 
  - master