testStage : 
  image: docker
  stage: test
  services:
    - docker:dind
  before_script:
    - docker build -t amarnaththillai/docker-react -f Dockerfile.dev .
  script:
    - docker run amarnaththillai/docker-react npm run test -- --coverage

production: 
  image: fedora
  stage: deploy
  script:
  - dnf update -y
  - dnf install -y ruby-devel
  - gem install dpl
  - dpl --provider="elasticbeanstalk" --access-key-id="$AWS_DOCKER_REACT_ACCESS_KEY" --secret-access-key="$AWS_DOCKER_REACT_SECRECT_KEY" --app="docker-react" --env="DockerReact-env" --region="eu-central-1"  --bucket_name="elasticbeanstalk-eu-central-1-852664985265" --bucket_path="docker-react"
  only: 
  - master