sudo: required
services: 
  - docker

before_install:
  - docker build -t amarnaththillai/docker-react -f Dockerfile.dev .

script:
  - docker run amarnaththillai/docker-react npm run test -- --coverage